spring:
  application:
    name: social-media
  datasource:
    url: jdbc:mysql://localhost:3306/social_media_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret: "b4f9e1c0d4a6e7f2a9d3b7f6c2e8a1d4f5c9b2a7e3d8f1c6b0a9d4f7e2c5b8a1"
    ttl-ms: 86400000